apiVersion: v1
kind: Secret
metadata:
  name: pacds-auth
  namespace: pacds
type: Opaque
stringData:
  tokens: "dev-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: pacds-git
  namespace: pacds
type: Opaque
stringData:
  token: "not-used"
