apiVersion: v1
kind: ConfigMap
metadata:
  name: service-registry
  namespace: pacds
data:
  registry.json: |
    {
      "checkout-service": "rophy/tostada",
      "user-service": "teams/platform/user-mgmt"
    }
