"""Master list of replay cases and candidates: source, created date and status, with each model's training cutoff.

Usage: python -m tests.replay.catalog [--check] [--after YYYY-MM-DD] [--cases-dir DIR [--cutoff MODEL=YYYY-MM-DD ...]]
  (no args)    rewrite tests/replay/CATALOG.md from every case.json in cases/ and candidates/
  --check      exit 1 if the catalog is out of date
  --after      print the ids of cases and candidates created after this date (e.g. a model's cutoff)
  --cases-dir  a case set elsewhere (tests/replay/casebook.py): its catalog is DIR/CATALOG.md, with each case's
               review status, and model cutoffs only as given with --cutoff
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

from tests.replay.harness import CANDIDATES_DIR, CASES_DIR

CATALOG = Path(__file__).parent / "CATALOG.md"
# Knowledge cutoffs of the models we evaluate with: a case created after a model's cutoff cannot be in its training data.
MODEL_CUTOFFS = {"gpt-6-luna": "2026-05-18", "plugsky-plus": "2025-06-30"}  # plugsky-plus: month only, per Plugsky's listing
CLASSES = {"A": "other system", "B": "user error", "C": "infrastructure", "D": "bug"}


def source_of(case: dict) -> str:
    if case.get("source"):
        return case["source"]
    found = re.match(r"https://github\.com/([^/]+/[^/]+)/issues/", case.get("issue_url", ""))
    return f"github:{found[1]}" if found else "unknown"


def load_all(roots: tuple[Path, ...] = (CASES_DIR, CANDIDATES_DIR), base: Path = CATALOG.parent) -> list[dict]:
    rows = []
    for root in roots:
        for path in sorted(root.glob("*/case.json")):
            case = json.loads(path.read_text())
            rows.append({
                "id": case["id"],
                "dir": path.parent.relative_to(base).as_posix(),
                "set": case.get("set", "clear"),
                "truth": case.get("truth") or "-",
                "tier": case.get("tier", "certain") if case.get("truth") else "-",
                "status": case.get("status") or ("labeled" if case.get("truth") else "draft"),
                "source": source_of(case),
                "created": (case.get("created_at") or "")[:10],
                "url": case.get("issue_url") or "",
                "title": case["report"].splitlines()[0].strip() if case.get("report") else "",
                "baseline": case.get("baseline_p_truth") or [],
            })
    return sorted(rows, key=lambda row: (row["created"], row["id"]), reverse=True)


def render(rows: list[dict], *, cutoffs: dict[str, str] = MODEL_CUTOFFS, external: bool = False) -> str:
    sets = sorted({row["set"] for row in rows}, key=["clear", "hard", "candidate"].index)
    intro = ([
        "Generated by `python -m tests.replay.catalog --cases-dir` from every `case.json` in this case set; do not edit by hand.",
        "",
        "- **Sets:** `clear` and `hard` are labeled cases screened with the no-code baseline; `candidate` cases are not",
        "  screened yet. **Status** is the review state (`python -m tests.replay.casebook status`); only labeled cases run.",
    ] if external else [
        "Generated by `python -m tests.replay.catalog` from every `case.json` in `cases/` and `candidates/`; do not edit by hand.",
        "",
        "- **Sets:** `clear` and `hard` are reviewed cases (`cases/`). `candidate` cases (`candidates/`) are screened",
        "  but not yet baseline-filtered or reviewed; run them with `--candidates`.",
    ])
    lines = [
        "# Replay case catalog",
        "",
        *intro,
        "- **Baseline:** mean p(truth) of the no-code baseline over its runs; a case is hard when it is 0.6 or less.",
        "- **Created:** when the original report was posted. A case created after a model's knowledge cutoff cannot be",
        "  in that model's training data; `python -m tests.replay.catalog --after <date>` lists them.",
        "",
        "## Model cutoffs",
        "",
        "| Model | Knowledge cutoff | " + " | ".join(f"{name} after cutoff" for name in sets) + " |",
        "|---|---|" + "---|" * len(sets),
    ]
    for model, cutoff in cutoffs.items():
        counts = [sum(1 for row in rows if row["set"] == name and row["created"] > cutoff) for name in sets]
        totals = [sum(1 for row in rows if row["set"] == name) for name in sets]
        lines.append(f"| {model} | {cutoff} | " + " | ".join(f"{n} of {t}" for n, t in zip(counts, totals)) + " |")
    lines += ["", "## Summary", "", "| Source | " + " | ".join(sets) + " |", "|---|" + "---|" * len(sets)]
    by_source = Counter((row["source"], row["set"]) for row in rows)
    for source in sorted({row["source"] for row in rows}):
        lines.append(f"| {source} | " + " | ".join(str(by_source[(source, name)]) for name in sets) + " |")
    by_class = Counter((row["truth"], row["set"]) for row in rows)
    lines += ["", "| Class | " + " | ".join(sets) + " |", "|---|" + "---|" * len(sets)]
    for letter, name in CLASSES.items():
        lines.append(f"| {letter} {name} | " + " | ".join(str(by_class[(letter, s)]) for s in sets) + " |")
    marks = list(cutoffs.items())
    status = "Status | " if external else ""
    lines += ["", "## Cases", "", "Newest first. A ✓ marks a case created after that model's cutoff.", "",
              f"| Created | Case | {status}Set | Class | Review | Baseline | Source | " + " | ".join(f"> {model}" for model, _ in marks) + " | Title |",
              "|---|---|---|---|---|---|---|" + ("---|" if external else "") + "---|" * len(marks) + "---|"]
    for row in rows:
        title = row["title"].replace("|", "\\|")
        title = title if len(title) <= 80 else title[:77] + "..."
        after = " | ".join("✓" if row["created"] > cutoff else "" for _, cutoff in marks)
        runs = row.get("baseline") or []
        baseline = f"{sum(runs) / len(runs):.2f}" if runs else ""
        source = f"[{row['source']}]({row['url']})" if row["url"] else row["source"]
        state = f"{row['status']} | " if external else ""
        lines.append(f"| {row['created']} | [{row['id']}]({row['dir']}/case.json) | {state}{row['set']} | {row['truth']} | {row['tier']} | {baseline} | "
                     f"{source} | {after} | {title} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if CATALOG.md is out of date")
    parser.add_argument("--after", help="print the ids of cases created after this date (YYYY-MM-DD)")
    parser.add_argument("--cases-dir", type=Path, help="a case set outside the repository")
    parser.add_argument("--cutoff", action="append", default=[], help="MODEL=YYYY-MM-DD, with --cases-dir (repeatable)")
    args = parser.parse_args()
    catalog, cutoffs, external = CATALOG, MODEL_CUTOFFS, False
    if args.cases_dir:
        catalog, external = args.cases_dir / "CATALOG.md", True
        cutoffs = dict(item.split("=", 1) for item in args.cutoff)
        rows = load_all((args.cases_dir,), args.cases_dir)
    else:
        rows = load_all()
    if args.after:
        for row in rows:
            if row["created"] > args.after:
                print(f"{row['created']}  {row['set']:9}  {row['truth']}  {row['id']}")
        return
    text = render(rows, cutoffs=cutoffs, external=external)
    if args.check:
        if not catalog.exists() or catalog.read_text() != text:
            sys.exit(f"{catalog} is out of date: run python -m tests.replay.catalog" + (f" --cases-dir {args.cases_dir}" if external else ""))
        return
    catalog.write_text(text)
    print(f"wrote {catalog} ({len(rows)} cases)")


if __name__ == "__main__":
    main()
